### ISSUE TITLE
FAILED BINDER TRANSACTION 

### ISSUE THREAD

**Issue by waterdaan** [TreeFrogApps/Pure#1]
Hi

Thanks for this excellent example of the whole mediaservice / mediabrowser!!

There´s one thing stopping me from using MediaBrowser(Compat) and that is this error
com.treefrogapps.pure:pure_music_service E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1440184)
The app doesn´t crash but it shows nothing under All Music.

Yes I know, I´ve got a whole lot of music on my phone..... if I change a line in 
**buildPlayableMusicList(Context context, String parentId, String where, String[] whereClause, @Nullable String orderBy)** in **RetrieveBase** to
while (cursor.moveToNext() && cursor.getPosition() < 900); 
I do get the 900 results in All Music.

Would it be possible to fix that by using [MediaBrowserCompat.EXTRA_PAGE](https://developer.android.com/reference/android/support/v4/media/MediaBrowserCompat.html#EXTRA_PAGE) or is that only going to delay the inevitable?

By the way Artists and Albums works without any problems.
Thanks for your time
Daan

**Comment by TreeFrogApps** [comment]
The project is far from complete, and what you've said is something that I already have anticipated to be a problem - Intent Extras need to be marshalled and demarshalled and the Android Framework has a small, in comparson to phone specs nowadays, Parcelable size limit (which is shared between all apps, and can vary between phones/Android version).  

This is not a top priority for me to fix right now.  The actual mechanics and logic of getting round the problem aren't that difficult, in fact I've had to do something similar before.

**Comment by waterdaan** [comment]
Thank you for your reaction 

Like I said, this is the reason for me not to use MediaBrowser(Compat). If you know how to fix this,  could you point me in the right direction?
